In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')
%config Completer.use_jedi =False

In [2]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# CountVectorizer

In [3]:
cv = CountVectorizer()

In [4]:
l = ['cat', 'rat', 'lion','cat','tiger','lion','cat', 'rat', 'lion','cat','tiger','lion', 'elephant']
g = ['cat', 'rat', 'rat', 'elephant', 'kite','sun', 'hospital']

In [5]:
def countFreq(arr): 
  
    mp = dict() 
  

    for i in range(len(arr)): 
        if arr[i] in mp.keys(): 
            mp[arr[i]] += 1
        else: 
            mp[arr[i]] = 1
              
    return mp
  

In [6]:
countFreq(l),countFreq(g)

({'cat': 4, 'rat': 2, 'lion': 4, 'tiger': 2, 'elephant': 1},
 {'cat': 1, 'rat': 2, 'elephant': 1, 'kite': 1, 'sun': 1, 'hospital': 1})

In [7]:
cv1 = CountVectorizer()
l_=cv1.fit_transform(l)

In [8]:
cv1.vocabulary_

{'cat': 0, 'rat': 3, 'lion': 2, 'tiger': 4, 'elephant': 1}

In [11]:
l_.toarray()

array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0]], dtype=int64)

In [12]:
g_=cv1.transform(g)

In [14]:
 g_.toarray() # fit on l and with same transform g with cv1


array([[1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

# TFIDF


In [28]:
tfidf = TfidfVectorizer()

In [29]:
k = ['the cat', 'cat is clever', 'Ram needs study cleverly',' Ram has one cat' ]

In [31]:
l_tf = tfidf.fit_transform(k)

In [32]:
tfidf.get_feature_names()

['cat',
 'clever',
 'cleverly',
 'has',
 'is',
 'needs',
 'one',
 'ram',
 'study',
 'the']

In [33]:
tfidf.vocabulary_

{'the': 9,
 'cat': 0,
 'is': 4,
 'clever': 1,
 'ram': 7,
 'needs': 5,
 'study': 8,
 'cleverly': 2,
 'has': 3,
 'one': 6}

In [34]:
tfidf.idf_

array([1.22314355, 1.91629073, 1.91629073, 1.91629073, 1.91629073,
       1.91629073, 1.91629073, 1.51082562, 1.91629073, 1.91629073])

In [35]:
l_tf.toarray()

array([[0.53802897, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.84292635],
       [0.41137791, 0.64450299, 0.        , 0.        , 0.64450299,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.52547275, 0.        , 0.        ,
        0.52547275, 0.        , 0.41428875, 0.52547275, 0.        ],
       [0.36674667, 0.        , 0.        , 0.57457953, 0.        ,
        0.        , 0.57457953, 0.4530051 , 0.        , 0.        ]])