## SPAM Text Classification

- N Gram and Bi Gram
- BOW
- TF IDF


----

string - please turn your page

- Unigram: **please | turn | your | page**
- bigram: **please turn | turn your | your page**
- trigram: **please turn your | turn your page**

### Bag of words

``` x = ['I love NLP','NLP is super solid tool']```

|I| love| NLP| is |super|solid|tool|
|---|---|---|---|---|---|---|
|1|1|1|0|0|0|0|0|
|0|0|1|1|1|1|1|1|


### Term frequency

```TF(t) = (Number of times term t appears in a document) / (Total number of terms in the document)```


``` x = ['I love NLP','NLP is super solid tool']```

||I| love| NLP| is |super|solid|tool|
|---|---|---|---|---|---|---|---|
|0|0.33|.33|.33|0|0|0|0|0|
|1|0|0|0|.2|.2|.2|.2|.2|


### Inverse Term frequency

```TF(t) = log_e(Total number of documents / Number of documents with term t in it)```


``` x = ['I love NLP','NLP is super solid tool']```

||I| love| NLP| is |super|solid|tool|
|---|---|---|---|---|---|---|---|
|0|log(2/1)|log(2/1)|log(2/2)|log(2/1)|log(2/1)|log(2/1)|log(2/1)|log(2/1)|


### TFIDF

``` TF = it amplifies the value if word is present in single document multople times.
IDF = it penalizes if word is present in more documents```

**So the point to consider is , common word in all document should not be given importance and should be penalized** 

``` TFIDF = TF * IDF ```


### python code to calculate TFIDF and BOW

``` Bag of words - CountVectorizer```

``` python 
from sklearn.feature_extraction.text import CountVectorizer 
```


``` TFIDF  - TfidfVectorizer ```

``` python
from sklearn.feature_extraction.text import TfidfVectorizer
```


In [1]:
from sklearn.feature_extraction.text import CountVectorizer 
import pandas as pd

In [2]:
x = ['I love NLP','NLP is super solid tool']
c=CountVectorizer()

In [3]:
count=c.fit_transform(x)

In [4]:
count.toarray()   # BOW

array([[0, 1, 1, 0, 0, 0],
       [1, 0, 1, 1, 1, 1]], dtype=int64)

In [5]:
c.get_feature_names()

['is', 'love', 'nlp', 'solid', 'super', 'tool']

In [6]:
pd.DataFrame(count.toarray(),columns=[c.get_feature_names()])

is love nlp solid super tool
0  0    1   1     0     0    0
1  1    0   1     1     1    1

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
tfidf = TfidfVectorizer()

In [9]:
t = tfidf.fit_transform(x)

In [10]:
t.toarray() #tfidf

array([[0.        , 0.81480247, 0.57973867, 0.        , 0.        ,
        0.        ],
       [0.47107781, 0.        , 0.33517574, 0.47107781, 0.47107781,
        0.47107781]])

In [11]:
tfidf.get_feature_names()

['is', 'love', 'nlp', 'solid', 'super', 'tool']

In [12]:
import pandas as pd
import numpy as np

In [13]:
pd.DataFrame(t.toarray(),columns=[tfidf.get_feature_names()])

is      love       nlp     solid     super      tool
0  0.000000  0.814802  0.579739  0.000000  0.000000  0.000000
1  0.471078  0.000000  0.335176  0.471078  0.471078  0.471078

In [14]:
## calculating the tfidf manually

df= pd.DataFrame(count.toarray(),columns=[c.get_feature_names()])
df_copy = df.copy()

In [15]:
## first TF manually
for index, row in enumerate(df.iterrows()):
    for col in row[1].index:
        df.loc[index,col] = df.loc[index, col]/sum(row[1].values)

In [16]:
df

is love  nlp solid super tool
0  0.0  0.5  0.5   0.0   0.0  0.0
1  0.2  0.0  0.2   0.2   0.2  0.2

In [17]:
# now IDF manually
df_copy=df_copy.astype(bool)

In [18]:
df_copy

is   love   nlp  solid  super   tool
0  False   True  True  False  False  False
1   True  False  True   True   True   True

In [19]:
df_copy['is'].sum() # total doc where the token exist

is    1
dtype: int64

In [20]:
df_copy.shape  # total number of document
doc_count = df_copy.shape[0]

In [21]:
tfidf_list=[]
for col in df_copy.columns:
    tfidf_list.append(np.log((doc_count+1)/(df_copy[col].sum()+1))+1)
    

In [22]:
tfidf_list

[1.4054651081081644,
 1.4054651081081644,
 1.0,
 1.4054651081081644,
 1.4054651081081644,
 1.4054651081081644]

In [23]:
#tfidf is object for tfidf. so idf manually and from algorithm are same
tfidf.idf_

array([1.40546511, 1.40546511, 1.        , 1.40546511, 1.40546511,
       1.40546511])

### Load dataset

In [24]:
data = pd.read_csv('spam.csv',encoding='latin-1')

In [25]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [26]:
data.isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5560
Unnamed: 4    5566
dtype: int64

In [27]:
# null value in column 3

data[data['Unnamed: 2'].isnull()].isnull().sum()

v1               0
v2               0
Unnamed: 2    5522
Unnamed: 3    5522
Unnamed: 4    5522
dtype: int64

In [28]:
# after knowing that column 4 and 5 are just repeatation of col 2, thn removing it.
data.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],inplace=True)

In [29]:
# renaming the column name
data.rename(columns={'v1':'Classification','v2':'Message'}, inplace=True)

In [30]:
data.head()

Classification                                            Message
0            ham  Go until jurong point, crazy.. Available only ...
1            ham                      Ok lar... Joking wif u oni...
2           spam  Free entry in 2 a wkly comp to win FA Cup fina...
3            ham  U dun say so early hor... U c already then say...
4            ham  Nah I don't think he goes to usf, he lives aro...

## Text cleaning 

In [31]:
import re 

```Lower case```

In [32]:

data['Message']=data['Message'].apply(lambda x: x.lower() )

```# contraction to expansion
```

In [33]:

contraction_mapping = {"ain't": "is not", "aren't": "are not","can't": "cannot", "'cause": "because", "could've": "could have", "couldn't": "could not", "didn't": "did not",  "doesn't": "does not", "don't": "do not", "hadn't": "had not", "hasn't": "has not", "haven't": "have not", "he'd": "he would","he'll": "he will", "he's": "he is", "how'd": "how did", "how'd'y": "how do you", "how'll": "how will", "how's": "how is",  "I'd": "I would", "I'd've": "I would have", "I'll": "I will", "I'll've": "I will have","I'm": "I am", "I've": "I have", "i'd": "i would", "i'd've": "i would have", "i'll": "i will",  "i'll've": "i will have","i'm": "i am", "i've": "i have", "isn't": "is not", "it'd": "it would", "it'd've": "it would have", "it'll": "it will", "it'll've": "it will have","it's": "it is", "let's": "let us", "ma'am": "madam", "mayn't": "may not", "might've": "might have","mightn't": "might not","mightn't've": "might not have", "must've": "must have", "mustn't": "must not", "mustn't've": "must not have", "needn't": "need not", "needn't've": "need not have","o'clock": "of the clock", "oughtn't": "ought not", "oughtn't've": "ought not have", "shan't": "shall not", "sha'n't": "shall not", "shan't've": "shall not have", "she'd": "she would", "she'd've": "she would have", "she'll": "she will", "she'll've": "she will have", "she's": "she is", "should've": "should have", "shouldn't": "should not", "shouldn't've": "should not have", "so've": "so have","so's": "so as", "this's": "this is","that'd": "that would", "that'd've": "that would have", "that's": "that is", "there'd": "there would", "there'd've": "there would have", "there's": "there is", "here's": "here is","they'd": "they would", "they'd've": "they would have", "they'll": "they will", "they'll've": "they will have", "they're": "they are", "they've": "they have", "to've": "to have", "wasn't": "was not", "we'd": "we would", "we'd've": "we would have", "we'll": "we will", "we'll've": "we will have", "we're": "we are", "we've": "we have", "weren't": "were not", "what'll": "what will", "what'll've": "what will have", "what're": "what are",  "what's": "what is", "what've": "what have", "when's": "when is", "when've": "when have", "where'd": "where did", "where's": "where is", "where've": "where have", "who'll": "who will", "who'll've": "who will have", "who's": "who is", "who've": "who have", "why's": "why is", "why've": "why have", "will've": "will have", "won't": "will not", "won't've": "will not have", "would've": "would have", "wouldn't": "would not", "wouldn't've": "would not have", "y'all": "you all", "y'all'd": "you all would","y'all'd've": "you all would have","y'all're": "you all are","y'all've": "you all have","you'd": "you would", "you'd've": "you would have", "you'll": "you will", "you'll've": "you will have", "you're": "you are", "you've": "you have" }

def contraction_(x):
    for cont , exp in contraction_mapping.items():
        x = re.sub(cont,exp,x)
    return x    

In [34]:
data['Message']=data['Message'].apply(lambda x: contraction_(x))

```# remove emails
```

In [35]:

# first count the email present in all docs
data['Message'].apply(lambda x : len(re.findall('[a-zA-Z0-9_-]*@[a-zA-Z0-9_-]+\.com', x))).sum()

2

In [36]:
data['Message']=data['Message'].apply(lambda x : re.sub('[a-zA-Z0-9_-]*@[a-zA-Z0-9_-]+\.com',' ', x))

```# removing uRL```

In [37]:
# removing uRL
def find_URL(string): 
  
    # findall() has been used  
    # with valid conditions for urls in string 
    regex = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"
    url = re.findall(regex,string)       
    return [x[0] for x in url] 
      
# Driver Code 
string = 'My Profile: https://testing.org/user/ in  http://www.facebook.org/  www.google.com'
print("Urls: ", find_URL(string)) 

Urls:  ['https://testing.org/user/', 'http://www.facebook.org/', 'www.google.com']


In [38]:
# total url present in all the documents
data['Message'].apply(lambda x : len(find_URL(x))).sum()

116

In [39]:
# removing now all url
regex = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"
data['Message']=data['Message'].apply(lambda x : re.sub(regex, '', x))

``` removing special character and punctuation```

In [40]:
data['Message']=data['Message'].apply(lambda x : re.sub('[^\w ]+','',x))

```removing multiple spaces```

In [41]:
data['Message']=data['Message'].apply(lambda x : re.sub('\s{2,}',' ',x))

```Removing HTML Tag```


In [42]:
from bs4 import BeautifulSoup 
data['Message']=data['Message'].apply(lambda x : BeautifulSoup(x,'html').get_text().strip())


```remove accented chars```

In [43]:
import unicodedata
def remove_accented_chars(x):
    x = unicodedata.normalize('NFKD', x).encode('ascii','ignore').decode('utf-8','ignore')
    return x

In [44]:
data['Message']=data['Message'].apply(lambda x : remove_accented_chars(x))

``` remove stopwords```

In [45]:
from spacy.lang.en.stop_words import STOP_WORDS as stopwords

In [46]:
def remove_stopwords(x):
    return ' '.join([w for w in x.split() if w not in stopwords])

In [47]:
data['Message']=data['Message'].apply(lambda x : remove_stopwords(x))

```lemmatization```

In [48]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [49]:
def convert_to_root(x):
    doc= nlp(x)
    x_list=[]
    for w in doc:
        root = w.lemma_
        x_list.append(root)
    return ' '.join(x_list)

In [50]:
data['Message']=data['Message'].apply(lambda x : convert_to_root(x))

In [51]:
data['Classification'].value_counts()

ham     4825
spam     747
Name: Classification, dtype: int64

```removing most common words and rare words```

In [52]:
text= ' '.join(data['Message'])

In [53]:
len(text.split())

46755

In [54]:
len(text)

262136

In [55]:
(text.split())

['jurong',
 'point',
 'crazy',
 'available',
 'bugis',
 'n',
 'great',
 'world',
 'la',
 'e',
 'buffet',
 'cine',
 'get',
 'amore',
 'wat',
 'ok',
 'lar',
 'joke',
 'wif',
 'u',
 'oni',
 'free',
 'entry',
 '2',
 'wkly',
 'comp',
 'win',
 'fa',
 'cup',
 'final',
 'tkts',
 '21st',
 '2005',
 'text',
 'fa',
 '87121',
 'receive',
 'entry',
 'questionstd',
 'txt',
 'ratetc',
 'apply',
 '08452810075over18s',
 'u',
 'dun',
 'early',
 'hor',
 'u',
 'c',
 'nah',
 'think',
 'go',
 'usf',
 'life',
 'freemsg',
 'hey',
 'darling',
 '3',
 'week',
 'word',
 'like',
 'fun',
 'tb',
 'ok',
 'xxx',
 'std',
 'chgs',
 'send',
 'a150',
 'rcv',
 'brother',
 'like',
 'speak',
 'treat',
 'like',
 'aid',
 'patent',
 'request',
 'melle',
 'melle',
 'oru',
 'minnaminunginte',
 'nurungu',
 'vettam',
 'set',
 'callertune',
 'caller',
 'press',
 '9',
 'copy',
 'friend',
 'callertune',
 'winner',
 'value',
 'network',
 'customer',
 'select',
 'receivea',
 'a900',
 'prize',
 'reward',
 'claim',
 '09061701461',
 'claim'

In [56]:
text

'jurong point crazy available bugis n great world la e buffet cine get amore wat ok lar joke wif u oni free entry 2 wkly comp win fa cup final tkts 21st 2005 text fa 87121 receive entry questionstd txt ratetc apply 08452810075over18s u dun early hor u c nah think go usf life freemsg hey darling 3 week word like fun tb ok xxx std chgs send a150 rcv brother like speak treat like aid patent request melle melle oru minnaminunginte nurungu vettam set callertune caller press 9 copy friend callertune winner value network customer select receivea a900 prize reward claim 09061701461 claim code kl341 valid 12 hour mobile 11 month u r entitle update late colour mobile camera free mobile update co free 08002986030 go to home soon want talk stuff anymore tonight k cry today chance win cash 100 20000 pound txt csh11 send 87575 cost 150pday 6days 16 tsandcs apply reply hl 4 info urgent win 1 week free membership a100000 prize jackpot txt word claim 81010 tc lccltd pobox 4403ldnw1a7rw18 search right w

In [57]:
words = pd.Series(text.split())

In [58]:
words.value_counts().head(5)

u      1132
2       478
ur      384
go      349
not     325
dtype: int64

In [59]:
top3 = words.value_counts().head(3)

In [60]:
top3 = top3.index.tolist()

In [61]:
tail10 = words.value_counts().tail(10)

In [62]:
tail10=tail10.index.tolist()

In [63]:
# removing top 3 common and 10 rare words from each document
data['Message']=data['Message'].apply(lambda x : ' '.join([w for w in x.split() if w not in tail10 and w not in top3  ]))

In [95]:
data.head()

Classification                                            Message
0            ham  jurong point crazy available bugis n great wor...
1            ham                                ok lar joke wif oni
2           spam  free entry wkly comp win fa cup final tkts 21s...
3            ham                                    dun early hor c
4            ham                              nah think go usf life

### Data Preparation for training

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [74]:
 = TfidfVectorizer()
x = tfidf.fit_transform(data['Message'])

In [75]:
x = x.toarray()

In [89]:
x.shape

(5572, 8156)

In [91]:
data['Classification'].shape

(5572,)

In [92]:
X_train, X_test, y_train, y_test = train_test_split(x, data['Classification'], test_size=0.33, random_state=42)

In [94]:
X_train.shape, X_test.shape

((3733, 8156), (1839, 8156))

(5572, 2)


### Training the classifier

RandomForestClassifier

In [96]:
clf = RandomForestClassifier(n_estimators=100,n_jobs=-1)

In [97]:
clf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [98]:
y_pred = clf.predict(X_test)

In [99]:
accuracy_score(y_test,y_pred)

0.9711799891245242

In [100]:
confusion_matrix(y_test,y_pred)

array([[1587,    0],
       [  53,  199]], dtype=int64)

In [102]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.98      1587
        spam       1.00      0.79      0.88       252

   micro avg       0.97      0.97      0.97      1839
   macro avg       0.98      0.89      0.93      1839
weighted avg       0.97      0.97      0.97      1839



### SVC



In [110]:
clf = SVC( C =1000 ,gamma = 'auto')

In [111]:
clf.fit( X_train,y_train)

SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [112]:
y_pred = clf.predict(X_test)

In [113]:
accuracy_score(y_test,y_pred)

0.9488852637302883

In [114]:
confusion_matrix(y_test,y_pred)

array([[1584,    3],
       [  91,  161]], dtype=int64)

In [115]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.95      1.00      0.97      1587
        spam       0.98      0.64      0.77       252

   micro avg       0.95      0.95      0.95      1839
   macro avg       0.96      0.82      0.87      1839
weighted avg       0.95      0.95      0.94      1839



### checking model on real data

In [116]:
def predict(x):
    x = tfidf.transform([x])
    x=x.toarray()
    pred = clf.predict(x)
    return pred

In [120]:
predict('hey, i am fine, what about you')


array(['ham'], dtype=object)

In [134]:
predict('free entry wkly comp win fa cup final ')

array(['spam'], dtype=object)

### hurray !!!